---
- name: Setup Database Server
  hosts: db_servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run MySQL
      docker_container:
        name: mysql
        image: mysql:8.0
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: "student_db"
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_ROOT_HOST: "%"

- name: Setup App Server
  hosts: app_servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Run Spring Boot App
      docker_container:
        name: student-app
        image: "raghavendra76/student-app:latest"
        state: started
        pull: yes
        recreate: yes
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://172.31.20.80:3306/student_db?allowPublicKeyRetrieval=true&useSSL=false"
          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "root"
          # 👇 CATCH-ALL AWS CREDENTIALS (Fixes the S3 crash)
          AWS_ACCESS_KEY_ID: "{{ AWS_KEY }}"
          AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET }}"
          AWS_ACCESS_KEY: "{{ AWS_KEY }}"
          AWS_SECRET_KEY: "{{ AWS_SECRET }}"
