apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: springboot-container
        image: raghavendra76/student-app:latest
        imagePullPolicy: Always  # 👈 This ensures the fresh image is always pulled
        ports:
        - containerPort: 8080
        # Optional: Environment variables if your app needs them at runtime
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_S3_BUCKET
          value: "student-managementttttttt"