apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: springboot-route
spec:
  host: springboot-route-raghavendra76-dev.apps.rm3.7wse.p1.openshiftapps.com
  to:
    kind: Service
    name: springboot-service
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
